CREATE TABLE COMM(
	ORDER_ID BIGINT PRIMARY KEY,
	COMPANY VARCHAR (50),
	CITY  VARCHAR(50),
	CUSTOMER_AGE INT,
	ORDER_VALUE INT,
	DELIVERY_TIME_MIN INT,
	DISTANCE_KM DECIMAL(5,2),
	ITEMS_COUNT INT,
	PRODUCT_CATEGORY VARCHAR(50),
	PAYMENT_METHOD VARCHAR(50),
	CUSTOMER_RATING DECIMAL(2,1),
	DISCOUNT_APPLIED BOOLEAN,
	DELIVEY_PARTNER_RATING DECIMAL(2,1)
);
-- TABLE
SELECT * FROM COMM;

-- TOTAL REVENUE 
SELECT SUM(ORDER_VALUE) AS TOTAL_REVENUE
FROM COMM;

-- TOTAL  REVENUE OF EACH COMPANY
SELECT COMPANY, SUM(ORDER_VALUE) AS TOTA_REVENUE
FROM COMM
GROUP BY COMPANY
ORDER BY COMPANY;

-- THE AVERAGE ORDER VALUE(AOV)
SELECT COMPANY,ROUND(AVG(ORDER_VALUE),2) AS AVG_REVENUE
FROM COMM
GROUP BY COMPANY
ORDER BY AVG_REVENUE DESC;

-- WHICH CITIES GENERATE HIGHEST REVENUE?
SELECT CITY, PRODUCT_CATEGORY, SUM(ORDER_VALUE) AS REVENUE
FROM COMM
GROUP BY CITY,PRODUCT_CATEGORY
ORDER BY REVENUE DESC 
LIMIT 5;


--WHICH CATEGORIES GENERATE HIGHEST REVENUE
SELECT PRODUCT_CATEGORY, SUM(ORDER_VALUE) AS AVG_REVENUE
FROM COMM
GROUP BY PRODUCT_CATEGORY
ORDER BY AVG_REVENUE DESC
LIMIT 5;

-- WHICH AGE GROUPS SPENDS THE MOST
SELECT 
	CASE 
		WHEN CUSTOMER_AGE < 25 THEN 'UNDER 25'
		WHEN CUSTOMER_AGE BETWEEN 25 AND 34 THEN '25-34'
		WHEN CUSTOMER_AGE BETWEEN 35 AND 44 THEN '35-44'
		WHEN CUSTOMER_AGE BETWEEN 45 AND 54 THEN '45-54'
		ELSE '55+'
	END AS AGE_GROUP,
	AVG(ORDER_VALUE) AS AVG_ORDER_VALUE
FROM COMM
GROUP BY AGE_GROUP
ORDER BY AVG_ORDER_VALUE DESC;

--WHICH AGE GROUP USES DISCOUNTS THE MOST?
SELECT 
	CASE 
		WHEN CUSTOMER_AGE < 25 THEN 'UNDER 25'
		WHEN CUSTOMER_AGE BETWEEN 25 AND 34 THEN '25-34'
		WHEN CUSTOMER_AGE BETWEEN 35 AND 44 THEN '35-44'
		WHEN CUSTOMER_AGE BETWEEN 45 AND 54 THEN '45-54'
		ELSE '55+'
	END AS AGE_GROUP,
	ROUND(
		100.0* SUM(CASE WHEN DISCOUNT_APPLIED = TRUE THEN 1 ELSE 0 END)
		/COUNT(*),2	) AS DISCOUNT_USAGE_PERCENT
FROM COMM
GROUP BY AGE_GROUP
ORDER BY DISCOUNT_USAGE_PERCENT DESC;

-- WHICH PAYMENT METHODS ARE MOST PREFERRED
SELECT PAYMENT_METHOD,COUNT(*) AS TOTAL_ORDERS
FROM COMM
GROUP BY PAYMENT_METHOD
ORDER BY  TOTAL_ORDERS DESC;

--HOW DO DISCOUNTS IMPACT SPENDING
SELECT DISCOUNT_APPLIED,
AVG(ORDER_VALUE) AS AVG_ORDER_VALUE,
SUM(ORDER_VALUE) AS TOTAL_REVENUE,
COUNT(*) AS TOTAL_ORDERS 
FROM COMM
GROUP BY DISCOUNT_APPLIED;


--HOW DOES DELIVERY TIME IMPACT CUSTOMER SATISFACTION
SELECT CASE
	WHEN DELIVERY_TIME_MIN <= 15 THEN '0-15 MINS' 
	WHEN DELIVERY_TIME_MIN <= 30 THEN '16-30 MINS'
	WHEN DELIVERY_TIME_MIN <= 45 THEN '31-45 MINS'
	ELSE '45+ MINS'
	END AS DELIVERY_BUCKET,
	AVG(CUSTOMER_RATING) AS AVG_RATING
FROM COMM
GROUP BY DELIVERY_BUCKET;


--HOW DOES DELIVERY DISTANCE IMPACT ORDER VALUE
SELECT
    CASE
        WHEN DISTANCE_KM <= 2 THEN '0 - 2 KM'
        WHEN DISTANCE_KM <= 5 THEN '2 - 5 KM'
        WHEN DISTANCE_KM <= 8 THEN '5 - 8 KM'
        ELSE '8+ KM'
    END AS DISTANCE_BUCKET,
    AVG(ORDER_VALUE) AS AVG_ORDER_VALUE
FROM COMM
GROUP BY
    CASE
        WHEN DISTANCE_KM <= 2 THEN '0 - 2 KM'
        WHEN DISTANCE_KM <= 5 THEN '2 - 5 KM'
        WHEN DISTANCE_KM <= 8 THEN '5 - 8 KM'
        ELSE '8+ KM'
END;

--WHICH CITY HAS THE BEST CUSTOMER RATING
SELECT CITY,AVG(CUSTOMER_RATING) AS AVG_RATING
FROM COMM
GROUP BY CITY
ORDER BY AVG_RATING DESC;

--Does Higher Delivery Partner Rating Improve Customer Satisfaction?
SELECT
    DELIVEY_PARTNER_RATING,
    ROUND(AVG(CUSTOMER_RATING),2) AS AVG_CUSTOMER_RATING
FROM COMM
GROUP BY DELIVEY_PARTNER_RATING
ORDER BY DELIVEY_PARTNER_RATING DESC;


--DO HIGHER ORDER VALUES LEAD TO BETTER RATING
SELECT 
	CASE
		WHEN ORDER_VALUE < 300 THEN 'LOW'
		WHEN ORDER_VALUE < 600 THEN 'HIGH'
		ELSE 'HIGH'
		END AS ORDER_BUCKET,
		ROUND(AVG(CUSTOMER_RATING),2) AS AVG_RATING
		FROM COMM
		GROUP BY ORDER_BUCKET
		ORDER BY AVG_RATING DESC;
		